# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M9I
email: mehdi.aouadi@gmail.com
description: >
    Yet Another Tech Blog !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mehdi-aouadi.github.io" # the base hostname & protocol for your site
future: true
#twitter_username: jekyllrb
github_username:  mehdi-aouadi

# Build settings
markdown: kramdown
